// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-nKQ77iveZo5JruulrsoCNKy39F3VZ8',
    appId: '1:859031858528:web:50f8520cdbda5b8bc90205',
    messagingSenderId: '859031858528',
    projectId: 'chat-ai-speech-bridge',
    authDomain: 'chat-ai-speech-bridge.firebaseapp.com',
    storageBucket: 'chat-ai-speech-bridge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKhlep7mSA1953kbGksU2MRs0-ECWcsMY',
    appId: '1:859031858528:android:d73496efcfb1d954c90205',
    messagingSenderId: '859031858528',
    projectId: 'chat-ai-speech-bridge',
    storageBucket: 'chat-ai-speech-bridge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-pvvXi-LkFOCpSHXyzntg5BH6p-xn7q4',
    appId: '1:859031858528:ios:c7bfc8610a3a3afbc90205',
    messagingSenderId: '859031858528',
    projectId: 'chat-ai-speech-bridge',
    storageBucket: 'chat-ai-speech-bridge.appspot.com',
    iosClientId: '859031858528-5l6qir7bq6qd0o137saqn3136uph4a8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-pvvXi-LkFOCpSHXyzntg5BH6p-xn7q4',
    appId: '1:859031858528:ios:af44e56a583f9155c90205',
    messagingSenderId: '859031858528',
    projectId: 'chat-ai-speech-bridge',
    storageBucket: 'chat-ai-speech-bridge.appspot.com',
    iosClientId: '859031858528-7s4ivrg218f54misci36e8gevdkfq9us.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatFlutter.RunnerTests',
  );
}
